### ISSUE TITLE
Further explanation if what's happening

### ISSUE THREAD

**Issue by albfan** [gautric/DroolsAutomatedTest#1]
Hi, thanks for this tool. Is really hepful.

I suppose the excel for test is related with this rules:

src/main/resources/net/a/g/brms/dat/rule/excel/player.xls

![rules](https://user-images.githubusercontent.com/220968/65679414-54240700-e055-11e9-8303-4ae58d0857e7.png)

but is not obvious how you can change that and make your test

Adding some info on README.md or wiki about rules, test and how to modify for other rules or test would be awesome!

If we can run rules and test from a precompiled jar that would be terrifying!

**Comment by gautric** [comment]
@albfan 
adding some link and doc.
feel free to send me your feedback
